package com.kk3k.workouttracker.ViewModels

import android.app.Application
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.viewModelScope
import com.kk3k.workouttracker.db.AppDatabase
import com.kk3k.workouttracker.db.entities.BodyMeasurement
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.launch
import java.util.Calendar

class BodyMeasurementViewModel(application: Application) : AndroidViewModel(application) {
    private val bodyMeasurementDao = AppDatabase.getDatabase(application).bodyMeasurementDao()

    // Get all body measurements as Flow
    val allMeasurements: Flow<List<BodyMeasurement>> = bodyMeasurementDao.getAllBodyMeasurementsFlow()

    // Insert a new body measurement
    fun insertBodyMeasurement(bodyMeasurement: BodyMeasurement) {
        viewModelScope.launch {
            bodyMeasurementDao.insert(bodyMeasurement)
        }
    }

    // Update an existing body measurement
    fun updateBodyMeasurement(bodyMeasurement: BodyMeasurement) {
        viewModelScope.launch {
            bodyMeasurementDao.update(bodyMeasurement)
        }
    }

    // Delete all body measurements
    fun deleteAllMeasurements() {
        viewModelScope.launch {
            bodyMeasurementDao.deleteAll()
        }
    }

    // Delete a specific body measurement
    fun deleteBodyMeasurement(bodyMeasurement: BodyMeasurement) {
        viewModelScope.launch {
            bodyMeasurementDao.delete(bodyMeasurement)
        }
    }

    // Get a specific body measurement by ID
    fun getBodyMeasurementById(id: Int, callback: (BodyMeasurement?) -> Unit) {
        viewModelScope.launch {
            val bodyMeasurement = bodyMeasurementDao.getBodyMeasurementById(id)
            callback(bodyMeasurement)
        }
    }

    // Get body measurements by date
    fun getBodyMeasurementsByDate(date: Long): Flow<List<BodyMeasurement>> {
        return bodyMeasurementDao.getBodyMeasurementsByDate(date)
    }

    // Get the most recent body measurement
    fun getMostRecentBodyMeasurement(callback: (BodyMeasurement?) -> Unit) {
        viewModelScope.launch {
            val mostRecentMeasurement = bodyMeasurementDao.getMostRecentBodyMeasurement()
            callback(mostRecentMeasurement)
        }
    }

    // Get the count of all body measurements
    fun getBodyMeasurementCount(callback: (Int) -> Unit) {
        viewModelScope.launch {
            val count = bodyMeasurementDao.getBodyMeasurementCount()
            callback(count)
        }
    }

    fun addSampleBodyMeasurements() {
        viewModelScope.launch {
            val calendar = Calendar.getInstance()
            val measurements = mutableListOf<BodyMeasurement>()

            for (i in 1..10) {
                val date = calendar.timeInMillis // Get current time in milliseconds

                // Create a sample body measurement
                val bodyMeasurement = BodyMeasurement(
                    uid = 0, // Auto-generated by Room if the primary key is set to auto-generate
                    date = date,
                    weight = 60 + i, // Example weight increasing by 1 kg each month
                    biceps = 30 + i, // Example biceps size increasing
                    triceps = 25 + i,
                    chest = 90 + i,
                    waist = 80 + i,
                    hips = 95 + i,
                    thighs = 50 + i,
                    calves = 40 + i,
                    notes = "Sample measurement for month $i"
                )

                measurements.add(bodyMeasurement)

                // Add one month to the calendar
                calendar.add(Calendar.MONTH, 1)
            }

            // Insert all measurements into the database
            bodyMeasurementDao.insertAll(*measurements.toTypedArray())
        }
    }

}
